-- TODO: fix PRODUCTION_YEAR_MONTH values
insert into CARS(BRAND, COLOUR, FUEL_TYPE, INSURANCE, MILEAGE, MODEL, PRODUCTION_YEAR_MONTH, VIN)
values ('Mazda', 'SOUL_RED', 'GASOLINE', true, 100, '6', null, '123456');

insert into CARS(BRAND, COLOUR, FUEL_TYPE, INSURANCE, MILEAGE, MODEL, PRODUCTION_YEAR_MONTH, VIN)
values ('Mazda', 'BlUE', 'GASOLINE', true, 100, '5', null, 'aBCD123');